---
abstract: 'Interface to Colors TV Programmes Schedules.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  HTTP::Request: 1.40
  LWP::UserAgent: 2.33
  Moose: 2.0006
  Moose::Util::TypeConstraints: 2.0006
  Readonly: 0
  Test::More: 0
  Time::localtime: 1.02
  XML::Simple: 2.14
  namespace::clean: 0.20
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TV-ProgrammesSchedules-Colors
provides:
  TV::ProgrammesSchedules::Colors:
    file: lib/TV/ProgrammesSchedules/Colors.pm
    version: 0.03
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
